<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
	public function findAllPublish()
	{
		return $this->createQueryBuilder('a')
				->andWhere('a.isPublish = :isPublish')
				->setParameter('isPublish', true)
				->getQuery()
				->execute();
	}
}
