<?php

namespace AppBundle\Repository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBandViaTag($id){
		$qb = $this->createQueryBuilder('b')
				->leftJoin('b.tags', 't')
				->andWhere('t.id = :id')
				->setParameter('id', $id)
				->getQuery()
				->execute();

				return $qb;
	}
}
