<?php

namespace AppBundle\Repository;

/**
 * ConcertHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertHallRepository extends \Doctrine\ORM\EntityRepository
{
}
