<?php

namespace AppBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findVilleByConcertHall($id){
		return $this->createQueryBuilder('v')
					->innerJoin('v.concertHall', 'ch')
					->addSelect('ch')
					->andWhere('ch.id = :id')
					->setParameter('id', $id)
					->getQuery()
					->execute();
	}
}
