Admin: 
    path:    /admin
    defaults:
        _controller: AppBundle:Admin\Admin:index

Event_new:
    path:    /event/new
    defaults:
        _controller: AppBundle:Admin\Event:new

Event_add:
    path:    /event/add
    defaults:
        _controller: AppBundle:Admin\Event:add

Event_edit:
    path:    /event/{id}/edit
    defaults:
        _controller: AppBundle:Admin\Event:edit

Band_new:
    path:    /band/new
    defaults:
        _controller: AppBundle:Admin\Band:new
Band_add:
    path:    /band/add
    defaults:
        _controller: AppBundle:Admin\Band:add

Band_edit:
    path:    /band/{id}/edit
    defaults:
        _controller: AppBundle:Admin\Band:edit

Categ_new:
    path:    /categ/new
    defaults:
        _controller: AppBundle:Admin\Category:new
Categ_add:
    path:    /categ/add
    defaults:
        _controller: AppBundle:Admin\Category:add

Categ_edit:
    path:    /categ/{id}/edit
    defaults:
        _controller: AppBundle:Admin\Category:edit

Album_new:
    path:    /album/new
    defaults:
        _controller: AppBundle:Admin\Album:new
        
Album_add:
    path:    /album/add
    defaults:
        _controller: AppBundle:Admin\Album:add

Album_edit:
    path:    /album/{id}/edit
    defaults:
        _controller: AppBundle:Admin\Album:edit
