
Home:
    path:    /home
    defaults:
        _controller: AppBundle:Home:index

Album:
    resource: "@AppBundle/Resources/config/routes/album.yml"
    prefix: /   

Event:
    resource: "@AppBundle/Resources/config/routes/event.yml"
    prefix: /

User:
    resource: "@AppBundle/Resources/config/routes/user.yml"
    prefix: /

Admin:
    resource: "@AppBundle/Resources/config/routes/admin.yml"
    prefix: /