
Album:
    resource: "@AppBundle/Resources/config/routes/album.yml"
    prefix: /   

Event:
    resource: "@AppBundle/Resources/config/routes/event.yml"
    prefix: /

User:
    resource: "@AppBundle/Resources/config/routes/user.yml"
    prefix: /