Album_index:
    path:    /album_admin
    defaults:
        _controller: AppBundle:Admin\Album:index

Album_new:
    path:    /album/new
    defaults:
        _controller: AppBundle:Admin\Album:new

Album_add:
    path:    /album/add
    defaults:
        _controller: AppBundle:Admin\Album:add

Album_edit:
    path:    /album/{id}/edit
    defaults:
        _controller: AppBundle:Admin\Album:edit

Album_delete:
    path:    /album/{id}/delete
    defaults:
        _controller: AppBundle:Admin\Album:delete